### ISSUE TITLE
Request: `background` parameter for `fc`

### ISSUE THREAD

**Issue by liboxun** [Hon-lab/pySpade#1]
Thanks for making `pySpade`! I've had good results from it for my dataset. 

Just as the user has the choice of background cells (e.g., cells with non-targeting gRNAs only) in `DEobs` and `DErand`, can you make that available for `fc`, too? It will help with a quick, first-pass look at the data with the right background.

**Comment by yihan1119** [comment]
Please see the latest version 0.1.3, background can be chosen with -b in `fc`.
